# Python Script for Generating a Data Set

In [1]:
import pandas as pd
import numpy as np

# set the number of rows
num_rows = 4000

# create an empty data frame
df = pd.DataFrame()

# creating a list of study hour--------------------------
sh=np.random.randint(low=0, high= 8,size=num_rows)
df['Study_hour']=sh


# creating a list for Assignment marks --------------------------------
assign=list()
for i in range(len(sh)):
    if sh[i]==0:
        temp=np.random.randint(1,3)
        assign.append(temp)
        
    elif sh[i]==1:
        temp=np.random.randint(1,3)
        assign.append(temp)
    
    elif sh[i]==2:
        temp=np.random.randint(2,4)
        assign.append(temp)
    
    elif sh[i]==3:
        temp=np.random.randint(3,5)
        assign.append(temp)
     
    elif sh[i]==4:
        temp=np.random.randint(3,6)
        assign.append(temp)
     
    elif sh[i]==5:
        temp=np.random.randint(4,6)
        assign.append(temp)
     
    elif sh[i]==6:
        assign.append(5)
    
    elif sh[i]==7:
        assign.append(5)
        
df['Assignment']=assign


# creating a list for Attendance marks -------------------------
atten=list()
for i in range(len(sh)):
    if sh[i]==0:
        temp=np.random.randint(2,5)
        atten.append(temp)
        
    elif sh[i]==1:
        temp=np.random.randint(3,5)
        atten.append(temp)
    
    elif sh[i]==2:
        temp=np.random.randint(3,6)
        atten.append(temp)
    
    elif sh[i]==3:
        temp=np.random.randint(3,6)
        atten.append(temp)
     
    elif sh[i]==4:
        temp=np.random.randint(3,6)
        atten.append(temp)
     
    elif sh[i]==5:
        temp=np.random.randint(3,6)
        atten.append(temp)
     
    elif sh[i]==6:
        atten.append(5)
    
    elif sh[i]==7:
        atten.append(5)
        
df['Attendance']=atten


# creating a list for Quiz1 marks ----------------------
quiz1=list()
for i in range(len(sh)):
    if sh[i]==0:
        temp=np.random.randint(1,3)
        quiz1.append(temp)
        
    elif sh[i]==1:
        temp=np.random.randint(1,3)
        quiz1.append(temp)
    
    elif sh[i]==2:
        temp=np.random.randint(1,4)
        quiz1.append(temp)
    
    elif sh[i]==3:
        temp=np.random.randint(2,5)
        quiz1.append(temp)
     
    elif sh[i]==4:
        temp=np.random.randint(3,5)
        quiz1.append(temp)
     
    elif sh[i]==5:
        temp=np.random.randint(4,6)
        quiz1.append(temp)
     
    elif sh[i]==6:
        quiz1.append(5)
    
    elif sh[i]==7:
        quiz1.append(5)
        
df['Quiz_one']=quiz1


# creating a list for Quiz2 marks ---------------------------
quiz2=list()
for i in range(len(sh)):
    if sh[i]==0:
        temp=np.random.randint(1,3)
        quiz2.append(temp)
        
    elif sh[i]==1:
        temp=np.random.randint(1,3)
        quiz2.append(temp)
    
    elif sh[i]==2:
        temp=np.random.randint(1,4)
        quiz2.append(temp)
    
    elif sh[i]==3:
        temp=np.random.randint(2,5)
        quiz2.append(temp)
     
    elif sh[i]==4:
        temp=np.random.randint(3,5)
        quiz2.append(temp)
     
    elif sh[i]==5:
        temp=np.random.randint(4,6)
        quiz2.append(temp)
     
    elif sh[i]==6:
        quiz2.append(5)
    
    elif sh[i]==7:
        quiz2.append(5)
        
df['Quiz_two']=quiz2


# creating a list for Midsem marks ---------------------------
mid=list()
for i in range(len(sh)):
    if sh[i]==0:
        temp=np.random.randint(1,6)
        mid.append(temp)
        
    elif sh[i]==1:
        temp=np.random.randint(5,11)
        mid.append(temp)
    
    elif sh[i]==2:
        temp=np.random.randint(10,16)
        mid.append(temp)
    
    elif sh[i]==3:
        temp=np.random.randint(15,20)
        mid.append(temp)
     
    elif sh[i]==4:
        temp=np.random.randint(20,25)
        mid.append(temp)
     
    elif sh[i]==5:
        temp=np.random.randint(23,28)
        mid.append(temp)
     
    elif sh[i]==6:
        temp=np.random.randint(25,30)
        mid.append(temp)
     
    elif sh[i]==7:
        temp=np.random.randint(27,31)
        mid.append(temp)
df['Midsem']=mid


# creating a list for Endsem marks ---------------------------
end=list()
for i in range(len(sh)):
    if sh[i]==0:
        temp=np.random.randint(2,10)
        end.append(temp)
        
    elif sh[i]==1:
        temp=np.random.randint(6,16)
        end.append(temp)
    
    elif sh[i]==2:
        temp=np.random.randint(8,19)
        end.append(temp)
    
    elif sh[i]==3:
        temp=np.random.randint(15,26)
        end.append(temp)
     
    elif sh[i]==4:
        temp=np.random.randint(24,36)
        end.append(temp)
     
    elif sh[i]==5:
        temp=np.random.randint(30,42)
        end.append(temp)
     
    elif sh[i]==6:
        temp=np.random.randint(38,47)
        end.append(temp)
     
    elif sh[i]==7:
        temp=np.random.randint(42,51)
        end.append(temp)
df['Endsem']=end


# creating a column to know pass or fail
pf=list()
for i in range(len(sh)):
    total=0
    for j in range(1,7):
        total+=df.iloc[i][j]
    if total>=35:
        pf.append("pass")
    else:
        pf.append("fail")
df['Pass_Fail']=pf

In [2]:
df

,Study_hour,Assignment,Attendance,Quiz_one,Quiz_two,Midsem,Endsem,Pass_Fail
0,3,3,3,4,2,19,21,pass
1,1,1,4,1,2,6,14,fail
2,4,3,3,4,3,24,32,pass
3,6,5,5,5,5,26,43,pass
4,6,5,5,5,5,29,42,pass
5,6,5,5,5,5,27,41,pass
6,1,1,4,1,2,5,9,fail
7,6,5,5,5,5,29,45,pass
8,1,1,3,1,1,10,10,fail
9,6,5,5,5,5,25,45,pass
10,4,5,3,4,3,22,31,pass
11,7,5,5,5,5,29,50,pass
12,1,2,3,2,2,6,13,fail
13,5,4,3,4,4,27,39,pass
14,5,4,4,4,5,27,30,pass
15,4,5,5,3,3,24,35,pass
16,4,3,5,4,3,23,25,pass
17,4,4,5,3,3,20,30,pass
18,7,5,5,5,5,28,49,pass
19,7,5,5,5,5,29,45,pass
20,2,3,4,1,1,12,16,pass
21,6,5,5,5,5,25,42,pass
22,7,5,5,5,5,28,43,pass
23,1,2,3,1,1,5,10,fail
24,6,5,5,5,5,25,41,pass
25,5,5,4,4,4,24,38,pass
26,4,4,5,3,4,24,29,pass
27,7,5,5,5,5,28,46,pass
28,4,5,3,3,3,21,35,pass
29,6,5,5,5,5,27,43,pass
...,...,...,...,...,...,...,...,...
3970,4,4,4,4,3,22,33,pass
3971,3,3,5,3,4,17,20,pass
3972,1,1,3,1,1,9,12,fail
3973,2,2,4,2,1,10,15,fail
3974,1,1,4,1,2,7,14,fail
3975,0,1,3,1,2,1,7,fail
3976,7,5,5,5,5,27,44,pass
3977,5,4,4,5,4,24,30,pass
3978,5,5,3,4,5,24,33,pass
3979,2,3,5,3,1,12,17,pass
3980,3,4,3,4,4,17,21,pass
3981,5,4,5,4,5,26,37,pass
3982,6,5,5,5,5,26,46,pass
3983,3,4,5,4,2,15,15,pass
3984,1,2,3,2,1,8,12,fail
3985,3,4,5,3,2,19,18,pass
3986,0,2,3,2,1,4,7,fail
3987,2,3,4,3,1,14,17,pass
3988,2,2,4,1,2,12,9,fail
3989,5,5,5,5,4,27,38,pass
3990,7,5,5,5,5,28,47,pass
3991,6,5,5,5,5,27,44,pass
3992,6,5,5,5,5,26,38,pass
3993,1,2,4,1,2,7,12,fail
3994,5,4,3,4,5,27,41,pass
3995,2,2,4,2,2,11,12,fail
3996,0,1,4,2,2,3,3,fail
3997,3,4,5,4,4,19,16,pass
3998,6,5,5,5,5,27,38,pass
3999,6,5,5,5,5,25,38,pass

In [3]:
# converting the Data Frame to CSV file

df.to_csv("DataSet.csv",index=False)